[package]
name = "rock-paper-scissors"
license = "MIT"
version = "0.2.1"
edition = "2021"
documentation = "https://docs.rs/rock-paper-scissors/0.2.1/rock_paper_scissors/"
description = "rock-paper-scissors is a rock paper scissors game api that allows user to make custom rock paper scissors implementations"

[dependencies]
rand = "0.9.0"
